In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
df=pd.read_csv("utf-8''iris(1).csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
df['species_cat']=lr.fit_transform(df.species)
df.sample(5,random_state=1)

sepal_length  sepal_width  petal_length  petal_width     species  \
14            5.8          4.0           1.2          0.2      setosa   
98            5.1          2.5           3.0          1.1  versicolor   
75            6.6          3.0           4.4          1.4  versicolor   
16            5.4          3.9           1.3          0.4      setosa   
131           7.9          3.8           6.4          2.0   virginica   

     species_cat  
14             0  
98             1  
75             1  
16             0  
131            2

In [16]:
X=df[['sepal_length','sepal_width','petal_length','petal_width']]
y=df['species_cat']
#X.sample(5,random_state=1)
y.sample(5,random_state=1)


14     0
98     1
75     1
16     0
131    2
Name: species_cat, dtype: int32

In [14]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [23]:
df['species_cat'].value_counts()

2    50
1    50
0    50
Name: species_cat, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=23)
X_train.shape,X_test.shape
X_train.head(),y_train.head()

(     sepal_length  sepal_width  petal_length  petal_width
 77            6.7          3.0           5.0          1.7
 29            4.7          3.2           1.6          0.2
 92            5.8          2.6           4.0          1.2
 23            5.1          3.3           1.7          0.5
 128           6.4          2.8           5.6          2.1, 77     1
 29     0
 92     1
 23     0
 128    2
 Name: species_cat, dtype: int32)

In [28]:
y_train.value_counts()

1    32
2    29
0    29
Name: species_cat, dtype: int64

In [22]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=23)
model = model.fit(X_train, y_train)
score = 100.0 * model.score(X_test, y_test)
print(f"Decision Tree prediction accuracy = {score:4.1f}%")

Decision Tree prediction accuracy = 96.7%


In [30]:
result=model.predict(X_test)
result

array([2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0,
       1, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 1, 2, 1, 0, 2])

CLASSIFICATION REPORT AND CONFUSION MATRIX

In [34]:
from sklearn.metrics import classification_report,confusion_matrix
result=model.predict(X_test)
Labels=['Setosa','Versicolor','Virginica']
print(classification_report(y_test,result,target_names=Labels))
print(confusion_matrix(y_test,result))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        21
  Versicolor       0.90      1.00      0.95        18
   Virginica       1.00      0.90      0.95        21

   micro avg       0.97      0.97      0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60

[[21  0  0]
 [ 0 18  0]
 [ 0  2 19]]


MAKING PLOT

In [39]:
from helper_code import mlplots as ml
ml.confusion(y_test,result,Labels,'Decsion Tree Classifiaction')

ModuleNotFoundError: No module named 'helper_code'